name: Copia dei File Generati

on:
    push:
        branches: [83-action]

jobs:
    copy:
        runs-on: ubuntu-latest

        steps:
        - name: Copia dei File
          uses: actions/checkout@v2

        - name: Copia dei Documenti Interni
          run : find docs/interni/ -name '*.pdf' -exec cp {} public/interni \;

        - name: Copia dei Documenti Esterni
          run : find docs/esterni/ -name '*.pdf' -exec cp {} public/esterni \;

        - name: Copia dei Verbali Interni
          run : find docs/verbali/interni/ -name '*.pdf' -exec cp {} public/interni/verbali \;

        - name: Copia dei Verbali Esterni
          run : find docs/verbali/esterni/ -name '*.pdf' -exec cp {} public/esterni/verbali \;

        - name: Commit dei File
          run : |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"

            git add *.pdf
            git commit -m "Aggiornamento Automatico Documenti"
